### ISSUE TITLE
Multiblocks 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [sguest/jei-multiblocks#4] opened 2024-02-18 20:24 UTC
jeimultiblocks-1.19.2-0.0.3.jar
This probably applies more to you than to fashion Engineering, there are also multiblocks, right?
https://github.com/BluSunrize/ImmersiveEngineering/issues/5868

**Comment by sguest** [comment] 2024-02-18 20:50
The log snippet you've included shows an exception, but generally a full log file is more useful because this snippet doesn't provide the larger context around the error. What's going on at the time, etc.

It's tough to say exactly where the issue is, because it *is* happening during this mod trying to load recipes, but the actual recipe loading logic that's throwing the error is in the IE code base. To try to narrow it down, what is the actual observed issue in-game in this case? Is it just the JEI plugin not working, or are the IE multiblocks failing to load? That is, can you actually assemble the IE multiblocks, look them up in the manual, etc. I'm wondering if something is changing the IE multiblock recipes or otherwise preventing them from loading correctly.

Also, is there a specific other mod that's causing these issues to start happening? You mention Engineer's Delight and Engineered Compatibility in the linked issue. If you remove one or both of those mods, does the issue still happen? Are there other mods installed at the same time? If there is a specific mod compatibility issue it can still be worth investigating, but it's important to narrow down the issue.

**Comment by Krimatoria** [comment] 2024-02-18 22:25
And I know I know ahaha) I remembered) The EMI mod does not show part of the multiblock recipes, I wrote to them. I'll find it right now)

**Comment by Krimatoria** [comment] 2024-02-18 22:31
I thought it would not be solved. I have started the build right now, clicked on the [multiblog ](https://github.com/emilyploszaj/emi/issues/427)in the EMI interface and it does not show how to create it. 

![image](https://github.com/sguest/jei-multiblocks/assets/106809386/5894ee68-17d4-4b65-845a-1c7ecbdb0d7e)

**Comment by sguest** [comment] 2024-02-19 02:59
This is a plugin for JEI. I've never heard of EMI before, but taking a look at the repo it doesn't mention any kind of cross-compatibility with JEI plugins. If it is supposed to work with JEI plugins, I'd say it's on that mod to maintain compatibility. If you run into an issue when running with JEI feel free to re-open this, but otherwise I'm going to close the issue.

**Closed by sguest** 2024-02-19 02:59 UTC
